name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'app.py'
      - 'examples/*'
      - 'requirements.txt'
      - 'requirements-cuda.txt'
      - 'prompt.txt'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/minicpm-o-2.6-events-parser:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/minicpm-o-2.6-events-parser:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minicpm-o-2.6-events-parser:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minicpm-o-2.6-events-parser:buildcache,mode=max
